### PR TITLE
Fix keep-alive

### PR DESCRIPTION
**Pull request by jakirkham**
* Disable running on forks (where this is not needed)
* Ensure this is able to push ( https://github.com/gautamkrishnar/keepalive-workflow/discussions/13#discussioncomment-5091693 )

### CODE REVIEW

**Comment by jakirkham** [comment]
Also the setting referenced in comment ( https://github.com/gautamkrishnar/keepalive-workflow/discussions/13#discussioncomment-5976548 ) was already enabled in [this repo's GH action settings]( https://github.com/conda-forge/webservices-dispatch-action/settings/actions ):

Screenshot 2023-08-21 at 4 18 02 PM

**Comment by beckermr** [comment]
I think the issue is the branch protections on main require the tests to have run, but the empty commit this action makes doesn't go through a pr.

**Comment by jakirkham** [comment]
Yeah that's what's discussed in this thread ( https://github.com/gautamkrishnar/keepalive-workflow/discussions/13 ). They propose the changes made by this PR (and the setting we already have enabled). IOW this PR should fix the issue

**Comment by beckermr** [comment]
Right yeah except that for a required review, these changes did not work. I guess we'll see.

**Comment by jakirkham** [comment]
Interesting only see this requirement in [the branch protection settings for `main`]( https://github.com/conda-forge/webservices-dispatch-action/settings/branch_protection_rules/18556853 ):

Screenshot 2023-08-21 at 4 51 22 PM

**Comment by beckermr** [comment]
Yep it is needed to enable GitHubs automerge. We can turn it off if you’d like.

**Comment by jakirkham** [comment]
IOW the require approvals would be under "Require a pull request before merging", which is unchecked currently

**Comment by jakirkham** [comment]
> Yep it is needed to enable GitHubs automerge. We can turn it off if you’d like.

Gotcha let's see if this PR is enough (assuming the changes here are reasonable). If not, we can revisit

Having to turn off automerge would be less than ideal

**Review by beckermr — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks Matt! 🙏

Merging so we can try this out. If we find other things are needed, happy to follow up 🙂

**Pull request merged**
